flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HTTP-4000.3.7
- JuicyPixels-3.2.8.1
- QuickCheck-2.9.2
- SHA-1.6.4.2
- StateVar-1.1.0.4
- adjunctions-4.3
- aeson-1.2.0.0
- asn1-encoding-0.9.5
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.1.1
- attoparsec-0.13.1.0
- base-compat-0.9.3
- base-orphans-0.6
- base64-bytestring-1.0.0.1
- bifunctors-5.4.2
- blaze-builder-0.4.0.2
- blaze-html-0.9.0.1
- blaze-markup-0.8.0.0
- byteable-0.1.1
- cabal-doctest-1.0.2
- case-insensitive-1.2.0.9
- cereal-0.5.4.0
- cmark-0.5.5.1
- comonad-5.0.1
- conduit-1.2.10
- connection-0.2.8
- contravariant-1.4
- cookie-0.4.2.1
- cryptonite-0.23
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- digest-0.0.1.2
- distributive-0.5.2
- dlist-0.8.0.2
- doctemplates-0.1.0.2
- exceptions-0.8.3
- extensible-exceptions-0.1.1.4
- fail-4.9.0.0
- filemanip-0.3.6.3
- foundation-0.0.9
- free-4.12.4
- haddock-library-1.4.3
- hashable-1.2.6.0
- hourglass-0.2.10
- hslua-0.4.1
- http-client-0.5.6.1
- http-client-tls-0.3.4.2
- http-types-0.9.1
- hxt-9.3.1.16
- hxt-charproperties-9.2.0.1
- hxt-regex-xmlschema-9.2.0.3
- hxt-unicode-9.0.2.4
- integer-logarithms-1.0.1
- kan-extensions-5.0.2
- lens-4.15.2
- lifted-base-0.2.3.10
- memory-0.14.5
- mime-types-0.1.0.7
- mmorph-1.1.0
- monad-control-1.0.1.0
- mtl-2.2.1
- network-2.6.3.1
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- pandoc-1.19.2.1
- pandoc-types-1.17.0.5
- parallel-3.2.1.1
- parsec-3.1.11
- pem-0.2.2
- prelude-extras-0.4.0.3
- primitive-0.6.2.0
- profunctors-5.2
- random-1.1
- reflection-2.1.2
- regex-base-0.93.2
- regex-pcre-builtin-0.94.4.8.8.35
- resourcet-1.1.9
- safe-0.3.14
- scientific-0.3.4.12
- semigroupoids-5.2
- semigroups-0.18.3
- skylighting-0.1.1.5
- socks-0.5.5
- stm-2.4.4.1
- streaming-commons-0.1.17
- syb-0.7
- tagged-0.8.5
- tagsoup-0.14.1
- temporary-1.2.0.4
- texmath-0.9.4
- text-1.2.2.2
- tf-random-0.5
- time-locale-compat-0.1.1.3
- tls-1.3.10
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-compat-0.4.3.1
- unordered-containers-0.2.8.0
- utf8-string-1.0.1.1
- uuid-types-1.0.3
- vector-0.12.0.1
- void-0.7.2
- x509-1.6.5
- x509-store-1.6.2
- x509-system-1.6.4
- x509-validation-1.6.5
- xml-1.3.14
- yaml-0.8.23
- zip-archive-0.3.0.6
- zlib-0.6.1.2
- pretty-show-1.6.13
- haskell-lexer-1.0.1
- optparse-applicative-0.13.2.0
- ansi-terminal-0.6.3
- ansi-wl-pprint-0.6.7.3
- deepseq-1.4.2.0
- Cabal-1.24.2.0
- binary-0.8.5.1
- path-0.6.1
- path-io-1.3.2
- bytestring-0.10.8.1
- containers-0.5.10.2
- directory-1.3.1.1
- pretty-1.1.3.5
- process-1.4.3.0
- time-1.6.0.1
- unix-2.7.2.2

resolver: ghc-8.0.1
